version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignored_updates:
      - match:
          dependency_name: "baconjs"
          version_requirement: "3.x"
